id: PF37F967F
initial_creation_type: input
source_metadata:
  Title: The Maṇicūḍa Study
  Editor: Handurukande
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  Mahāsattvamaṇicūḍamahārājabodhisattvāvadānam:
    Text Version: Romanized
    Input Personnel: Milan Shakya
    Input Date: '2015'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:55:12.873462'
last_modified_at: '2022-03-08T15:55:12.873524'
